services:
  # Web Service
  - type: web
    name: ipl-ticket-tracker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0

  # Background Worker
  - type: worker
    name: ipl-ticket-monitor
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python monitor.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0 